version: "3.6"

services:
  redis_queue:
    container_name: myproj_redis
    hostname: redis
    image: redis:latest
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always

  fast_api:
    container_name: intern_fast_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5057:5057"
    working_dir: /opt/workspace
    volumes:
      - ./:/opt/workspace
    depends_on:
      - redis_queue
    command: uvicorn api:app --host 0.0.0.0 --port 5057 --reload
